# SmartSpawnPoint Configuration

# Region-based spawns (priority)
region-spawns:
  # Example for "spawn" region
  - region: "spawn"
    # World where this region is located. Use "*" for all worlds.
    region-world: "world"
    # Type: "fixed" for exact coordinates, "random" for random location, "weighted_random" for weighted chances,
    # "none" to just apply actions without teleporting
    type: "fixed"
    # Location where player will respawn
    location:
      world: "world"
      x: 0
      y: 64
      z: 0
      yaw: 0
      pitch: 0
      require-safe: false  # Set to false for known safe locations to improve performance
    # Custom waiting room for this spawn point (optional)
    # Used if require-safe = true and the waiting room system is enabled.
    # The player will be teleported here temporarily while a safe location is being searched asynchronously.
    #
    # ⚠️ Important:
    # - If a valid safe location is not found within the async search timeout,
    #   or the server restarts/crashes during the process, players may remain here indefinitely.
    # - Always ensure players can escape from this room — via NPCs, pressure plates, portals, or other means.
    # - On RPG servers, consider building thematic waiting rooms near friendly towns, shrines, or other story-relevant areas.
    waiting-room:
      world: "world"
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0
    # Conditions - all must be true for this spawn to be used
    # Note: Players with OP status or "*" permission will automatically pass permission checks
    conditions:
      # Permission conditions
      permissions:
        - "smartspawnpoint.vip"
      # PlaceholderAPI conditions (placeholder operator value)
      # Supported operators: =, ==, !=, >, >=, <, <=
      placeholders:
        - "%player_level% > 10"
    # Actions executed on respawn
    # Note: These actions are only executed after the player has been successfully teleported
    # to their final respawn location. If using a waiting room, actions will NOT execute
    # until the player leaves the waiting room and reaches their actual spawn point.
    actions:
      # Messages to send to player
      messages:
        - "You have respawned at the spawn region!"
      # Commands to execute (as console)
      commands:
        # Multiple commands with different chances and conditions
        - command: "effect give %player% minecraft:resistance 30 1"
          chance: 100  # 100% chance to execute

        - command: "give %player% minecraft:golden_apple 1"
          chance: 50   # 50% chance to execute
          # Conditional chances based on player permissions or placeholders
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"
              weight: 80  # 80% chance for VIP players
            - type: "placeholder"
              value: "%player_level% > 20"  # For players with level > 20
              weight: 100

        - command: "give %player% minecraft:golden_apple 2"
          chance: 25   # 25% chance to execute
          # Conditional chances based on player permissions or placeholders
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"
              weight: 40  # 40% chance for VIP players
            - type: "placeholder"
              value: "%player_level% > 20"  # For players with level > 20
              weight: 50

  # Example for PvP arena with disabled party respawn
  - region: "pvp_arena"
    region-world: "*"  # Will work in any world
    type: "random"
    # Disable party respawn in this region
    party-respawn-disabled: true
    location:
      world: "world"
      min-x: -100
      max-x: 100
      min-y: 64
      max-y: 80
      min-z: -100
      max-z: 100
      require-safe: false  # Disable safe location check for better performance
    # Custom waiting room (only used if require-safe is true)
    waiting-room:
      world: "world"
      x: 0
      y: 90
      z: 0

  # Example for wilderness region with mixed location types
  - region: "wilderness"
    region-world: "world"
    type: "weighted_random"
    locations:
      # Fixed location with 70% chance
      - type: "fixed"
        location:
          world: "world"
          x: 100
          y: 64
          z: 100
          require-safe: false
        weight: 70  # 70% chance
        weight-conditions:
          - type: "permission"
            value: "smartspawnpoint.safe"
            weight: 90  # 90% chance for players with this permission
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world"
          x: 200
          y: 100
          z: 200
          yaw: 90
          pitch: 0
      # Random location with 30% chance
      - type: "random"
        location:
          world: "world"
          min-x: -200
          max-x: -100
          min-y: 64
          max-y: 80
          min-z: -200
          max-z: -100
          require-safe: false
        weight: 30  # 30% chance
        weight-conditions:
          - type: "permission"
            value: "smartspawnpoint.adventure"
            weight: 60  # 60% chance for adventure players
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world"
          x: 300
          y: 100
          z: 300

  # Example for RPG adventure zone with location-specific actions
  - region: "adventure_zone"
    region-world: "*"  # Works in any world
    type: "weighted_random"
    locations:
      - type: "fixed"
        location:
          world: "forest"
          x: 150
          y: 70
          z: 150
          require-safe: false
        weight: 50  # 50% chance
      - type: "fixed"
        location:
          world: "desert"
          x: 150
          y: 70
          z: 150
          require-safe: false
        weight: 50  # 50% chance
    actions:
      commands:
        # Apply slowness effect only in the forest world
        # Requires Player expansion: /papi ecloud download Player
        - command: "effect give %player% minecraft:slowness 60 2"
          chance: 0
          chance-conditions:
            - type: "placeholder"
              value: "%player_world% == forest"  # Only in forest world
              weight: 100
            - type: "permission"
              value: "smartspawnpoint.vip"  # Not for VIPs
              weight: 0

        # VIPs get night vision in all worlds, non-VIPs only in forest
        - command: "effect give %player% minecraft:night_vision 300 1"
          chance: 0
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"  # Only for VIPs
              weight: 100
            - type: "placeholder"
              value: "%player_world% == forest"  # Only in forest world
              weight: 100

        # Apply fire resistance in the desert world for everyone
        - command: "effect give %player% minecraft:fire_resistance 120 1"
          chance: 0
          chance-conditions:
            - type: "placeholder"
              value: "%player_world% == desert"  # Only in desert world
              weight: 100

        # VIPs get speed boost in all worlds, non-VIPs only in desert
        - command: "effect give %player% minecraft:speed 120 1"
          chance: 0
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"  # Only for VIPs
              weight: 100
            - type: "placeholder"
              value: "%player_world% == desert"  # Only in desert world
              weight: 100

        # Apply special effects based on WorldGuard regions
        # Requires WorldGuard expansion: /papi ecloud download WorldGuard
        - command: "effect give %player% minecraft:haste 120 1"
          chance: 0
          chance-conditions:
            - type: "placeholder"
              value: "%worldguard_region_name% == mining_zone"  # Only in mining zones
              weight: 100

  # Example for a spawn point that only executes actions without teleporting
  - region: "action_region"
    region-world: "world"
    type: "none"  # Don't teleport, just run actions
    actions:
      messages:
        - "You died in the action region! No teleport, just this message."
      commands:
        - command: "effect give %player% minecraft:regeneration 10 1"
          chance: 100
        # Example with multiple commands with different chances
        - command: "give %player% minecraft:cooked_beef 1"
          chance: 100  # Always give food
        - command: "give %player% minecraft:golden_apple 1"
          chance: 10   # 10% chance for golden apple
        - command: "give %player% minecraft:enchanted_golden_apple 1"
          chance: 1    # 1% chance for enchanted golden apple
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"
              weight: 5  # 5% chance for VIP players

# World-based spawns (secondary priority)
world-spawns:
  # Default world
  - world: "world"
    type: "fixed"
    location:
      x: 0
      y: 64
      z: 0
      require-safe: false
    # Custom waiting room for this world spawn
    waiting-room:
      world: "world"
      x: 0
      y: 120
      z: 0
    actions:
      messages:
        - "You have respawned in the overworld!"
      commands:
        - command: "effect give %player% minecraft:regeneration 5 1"
          chance: 100
        - command: "give %player% minecraft:bread 3"
          chance: 100

  # Nether world example with mixed location types and disabled party respawn
  - world: "world_nether"
    type: "weighted_random"
    # Disable party respawn in this world
    party-respawn-disabled: true
    locations:
      # Option 1: Return to main world
      - type: "fixed"
        location:
          world: "world"
          x: 0
          y: 64
          z: 0
          require-safe: false
        weight: 80
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world"
          x: 100
          y: 90
          z: 100
      # Option 2: Random location in the nether (more dangerous)
      - type: "random"
        location:
          world: "world_nether"
          min-x: -100
          max-x: 100
          min-y: 30
          max-y: 100
          min-z: -100
          max-z: 100
          require-safe: true
        weight: 20
        weight-conditions:
          - type: "permission"
            value: "smartspawnpoint.nether"
            weight: 50  # Higher chance for players with nether permission
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world_nether"
          x: 0
          y: 100
          z: 0
    # Custom waiting room for the whole spawn point (used if no custom location waiting room)
    waiting-room:
      world: "world"
      x: 0
      y: 150
      z: 0
    actions:
      messages:
        - "You died in the Nether!"
      commands:
        - command: "effect give %player% minecraft:fire_resistance 60 1"
          chance: 100
        - command: "give %player% minecraft:golden_carrot 2"
          chance: 50
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.nether"
              weight: 100  # 100% chance for nether players

  # End world example
  - world: "world_the_end"
    type: "fixed"
    location:
      world: "world"  # Respawn in overworld
      x: 0
      y: 64
      z: 0
      require-safe: false
    # Custom waiting room
    waiting-room:
      world: "world"
      x: 0
      y: 150
      z: 0
    actions:
      messages:
        - "You died in the End! Respawning in the overworld..."
      commands:
        - command: "effect give %player% minecraft:slow_falling 30 1"
          chance: 100
        - command: "effect give %player% minecraft:night_vision 30 1"
          chance: 70
        - command: "clear %player%" # Clear inventory on death in End
          chance: 10 # 10% chance to lose all items
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.end.protect"
              weight: 0 # 0% chance for players with protection permission

# General settings
settings:
  # Maximum attempts to find safe location for random spawns
  max-safe-location-attempts: 20

  # Radius to search for safe locations (smaller = better performance)
  safe-location-radius: 5

  # Enable debug mode for detailed logs
  debug-mode: true

  # Force a delayed teleport even if respawn event has been processed
  force-delayed-teleport: true

  # Waiting room settings
  # The waiting room system helps reduce lag by allowing the plugin to search for
  # safe spawn locations asynchronously. When a player dies and requires a safe location,
  # they'll be temporarily teleported to the waiting room while the plugin searches
  # for an appropriate safe location in the background.
  #
  # You can specify waiting rooms at three levels of precedence:
  # 1. Individual weighted location waiting room (highest priority)
  # 2. Spawn point waiting room (used if no location-specific room)
  # 3. Global waiting room (lowest priority, used as fallback)
  #
  # ⚠️ Players may stay here permanently if the plugin fails to find a valid safe location within the search timeout.
  # Always ensure this location is not a trap and provides an escape option.
  waiting-room:
    # Enable the waiting room system - recommended if you use require-safe: true anywhere
    enabled: true

    # Timeout for async safe location search (seconds)
    # If a safe location isn't found within this time, player stays in waiting room
    async-search-timeout: 5

    # Global waiting room location (used if no custom waiting room is specified)
    location:
      world: "world"
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0

  # Party system settings
  # The party system allows players to form groups and respawn near each other after death.
  party:
    # Enable party system
    enabled: true

    # Maximum number of players in a party
    # Set to 0 for unlimited
    max-size: 10

    # Maximum distance for party respawn (blocks)
    # Set to 0 for unlimited distance
    max-respawn-distance: 0

    # Cooldown between party respawn for same player (seconds)
    # Set to 0 for no cooldown
    respawn-cooldown: 0

    # "Walking Spawn Point" feature
    # Players with this permission will respawn at their death location
    # and serve as spawn points for other party members
    # This is useful for content creators or special players
    respawn-at-death:
      enabled: true
      permission: "smartspawnpoint.party.respawnatdeath"
      message: "&aYou have respawned at your death location as a walking spawn point"

    # Invitation expiry time (seconds)
    invitation-expiry: 60

    # Message settings
    messages:
      # Colors: You can use '&' for color codes
      prefix: "&8[&bParty&8] &r"
      invite-sent: "&aInvitation sent to %player%"
      invite-received: "&aYou've been invited to join %player%'s party. Type /smartspawnpoint party accept to join"
      invite-declined: "&c%player% has declined your party invitation"
      invite-expired: "&cParty invitation expired"
      party-joined: "&a%player% has joined your party!"
      party-left: "&c%player% has left the party"
      player-kicked: "&c%player% has been removed from the party"
      player-not-found: "&cPlayer not found or offline"
      not-in-party: "&cYou are not in a party"
      not-leader: "&cOnly the party leader can do this"
      player-not-in-party: "&cThis player is not in your party"
      leader-changed: "&a%player% is now the party leader"
      party-disbanded: "&cThe party has been disbanded"
      respawned-at-member: "&aYou have respawned at %player%'s location"
      respawn-mode-changed: "&aParty respawn mode set to: %mode%"
      respawn-target-set: "&aYou will now respawn at %player%'s location"
      respawn-disabled-region: "&cParty respawn is disabled in this region"
      respawn-disabled-world: "&cParty respawn is disabled in this world"
      respawn-cooldown: "&cYou must wait %time% seconds before using party respawn again"

  # List of materials considered unsafe (will avoid spawning on these)
  unsafe-materials:
    - "LAVA"
    - "FIRE"
    - "CACTUS"
    - "WATER"
    - "AIR"
    - "MAGMA_BLOCK"
    - "CAMPFIRE"
    - "SOUL_CAMPFIRE"
    - "WITHER_ROSE"
    - "SWEET_BERRY_BUSH"
