# SmartSpawnPoint Configuration

# Region-based spawns (priority)
region-spawns:
  # Example for "spawn" region
  - region: "spawn"
    # World where this region is located. Use "*" for all worlds.
    region-world: "world"
    # Type: "fixed" for exact coordinates, "random" for random location, "weighted_random" for weighted chances,
    # "none" to just apply actions without teleporting
    type: "fixed"
    # Location where player will respawn
    location:
      world: "world"
      x: 0
      y: 64
      z: 0
      yaw: 0
      pitch: 0
      require-safe: false  # Set to false by default to avoid lag
    # Custom waiting room for this spawn point (optional)
    # If waiting-room is enabled in settings and require-safe is true,
    # player will be teleported here temporarily while a safe location is found
    waiting-room:
      world: "world"
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0
    # Conditions - all must be true for this spawn to be used
    # Note: Players with OP status or "*" permission will automatically pass permission checks
    conditions:
      # Permission conditions
      permissions:
        - "smartspawnpoint.vip"
      # PlaceholderAPI conditions (placeholder operator value)
      # Supported operators: =, ==, !=, >, >=, <, <=
      placeholders:
        - "%player_level% > 10"
    # Actions executed on respawn
    actions:
      # Messages to send to player
      messages:
        - "You have respawned at the spawn region!"
      # Commands to execute (as console)
      commands:
        - command: "effect give %player% minecraft:resistance 30 1"
          chance: 100  # 100% chance to execute
        - command: "give %player% minecraft:golden_apple 1"
          chance: 50   # 50% chance to execute
          # Conditional chances based on player permissions or placeholders
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"
              weight: 80  # 80% chance for VIP players
            - type: "placeholder"
              value: "%player_level% > 20:100"  # 100% chance for players with level > 20
              weight: 100

  # Example for PvP arena - works in any world
  - region: "pvp_arena"
    region-world: "*"  # Will work in any world
    type: "random"
    location:
      world: "world"
      min-x: -100
      max-x: 100
      min-y: 64
      max-y: 80
      min-z: -100
      max-z: 100
      require-safe: false  # Disable safe location check to avoid lag
    # Custom waiting room (only used if require-safe is true)
    waiting-room:
      world: "world"
      x: 0
      y: 90
      z: 0

  # Example for wilderness region with mixed location types
  - region: "wilderness"
    region-world: "world"
    type: "weighted_random"
    locations:
      # Fixed location with 70% chance
      - type: "fixed"
        location:
          world: "world"
          x: 100
          y: 64
          z: 100
          require-safe: false
        weight: 70  # 70% chance
        weight-conditions:
          - type: "permission"
            value: "smartspawnpoint.safe"
            weight: 90  # 90% chance for players with this permission
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world"
          x: 200
          y: 100
          z: 200
          yaw: 90
          pitch: 0
      # Random location with 30% chance
      - type: "random"
        location:
          world: "world"
          min-x: -200
          max-x: -100
          min-y: 64
          max-y: 80
          min-z: -200
          max-z: -100
          require-safe: false
        weight: 30  # 30% chance
        weight-conditions:
          - type: "permission"
            value: "smartspawnpoint.adventure"
            weight: 60  # 60% chance for adventure players
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world"
          x: 300
          y: 100
          z: 300

  # Example for a spawn point that only executes actions without teleporting
  - region: "action_region"
    region-world: "world"
    type: "none"  # Don't teleport, just run actions
    actions:
      messages:
        - "You died in the action region! No teleport, just this message."
      commands:
        - command: "effect give %player% minecraft:regeneration 10 1"
          chance: 100
        # Example with multiple commands with different chances
        - command: "give %player% minecraft:cooked_beef 1"
          chance: 100  # Always give food
        - command: "give %player% minecraft:golden_apple 1"
          chance: 10   # 10% chance for golden apple
        - command: "give %player% minecraft:enchanted_golden_apple 1"
          chance: 1    # 1% chance for enchanted golden apple
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.vip"
              weight: 5  # 5% chance for VIP players

# World-based spawns (secondary priority)
world-spawns:
  # Default world
  - world: "world"
    type: "fixed"
    location:
      x: 0
      y: 64
      z: 0
      require-safe: false
    # Custom waiting room for this world spawn
    waiting-room:
      world: "world"
      x: 0
      y: 120
      z: 0
    actions:
      messages:
        - "You have respawned in the overworld!"
      commands:
        - command: "effect give %player% minecraft:regeneration 5 1"
          chance: 100
        - command: "give %player% minecraft:bread 3"
          chance: 100

  # Nether world example with mixed location types
  - world: "world_nether"
    type: "weighted_random"
    locations:
      # Option 1: Return to main world
      - type: "fixed"
        location:
          world: "world"
          x: 0
          y: 64
          z: 0
          require-safe: false
        weight: 80
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world"
          x: 100
          y: 90
          z: 100
      # Option 2: Random location in the nether (more dangerous)
      - type: "random"
        location:
          world: "world_nether"
          min-x: -100
          max-x: 100
          min-y: 30
          max-y: 100
          min-z: -100
          max-z: 100
          require-safe: true
        weight: 20
        weight-conditions:
          - type: "permission"
            value: "smartspawnpoint.nether"
            weight: 50  # Higher chance for players with nether permission
        # Custom waiting room for this specific location option
        waiting-room:
          world: "world_nether"
          x: 0
          y: 100
          z: 0
    # Custom waiting room for the whole spawn point (used if no custom location waiting room)
    waiting-room:
      world: "world"
      x: 0
      y: 150
      z: 0
    actions:
      messages:
        - "You died in the Nether!"
      commands:
        - command: "effect give %player% minecraft:fire_resistance 60 1"
          chance: 100
        - command: "give %player% minecraft:golden_carrot 2"
          chance: 50
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.nether"
              weight: 100  # 100% chance for nether players

  # End world example
  - world: "world_the_end"
    type: "fixed"
    location:
      world: "world"  # Respawn in overworld
      x: 0
      y: 64
      z: 0
      require-safe: false
    # Custom waiting room
    waiting-room:
      world: "world"
      x: 0
      y: 150
      z: 0
    actions:
      messages:
        - "You died in the End! Respawning in the overworld..."
      commands:
        - command: "effect give %player% minecraft:slow_falling 30 1"
          chance: 100
        - command: "effect give %player% minecraft:night_vision 30 1"
          chance: 70
        - command: "clear %player%" # Clear inventory on death in End
          chance: 10 # 10% chance to lose all items
          chance-conditions:
            - type: "permission"
              value: "smartspawnpoint.end.protect"
              weight: 0 # 0% chance for players with protection permission

  # Example for a world spawn that only executes actions without teleporting
  - world: "world_action"
    type: "none"  # Don't teleport, just run actions
    actions:
      messages:
        - "You died in the action world! Using default spawn."
      commands:
        - command: "give %player% minecraft:golden_carrot 5"
          chance: 100

# General settings
settings:
  # Maximum attempts to find safe location for random spawns
  max-safe-location-attempts: 20

  # Radius to search for safe locations (smaller = better performance)
  safe-location-radius: 5

  # Enable debug mode for detailed logs
  debug-mode: true

  # Force a delayed teleport even if respawn event has been processed
  force-delayed-teleport: true

  # Waiting room settings
  # The waiting room system helps reduce lag by allowing the plugin to search for
  # safe spawn locations asynchronously. When a player dies and requires a safe location,
  # they'll be temporarily teleported to the waiting room while the plugin searches
  # for an appropriate safe location in the background.
  #
  # If the search times out or fails to find a safe location, the player will remain
  # in the waiting room, which provides a fallback mechanism rather than potentially
  # unsafe spawn locations.
  #
  # You can specify waiting rooms at three levels of precedence:
  # 1. Individual weighted location waiting room (highest priority)
  # 2. Spawn point waiting room (used if no location-specific room)
  # 3. Global waiting room (lowest priority, used as fallback)
  waiting-room:
    # Enable the waiting room system - recommended if you use require-safe: true anywhere
    enabled: true

    # Timeout for async safe location search (seconds)
    # If a safe location isn't found within this time, player stays in waiting room
    async-search-timeout: 5

    # Global waiting room location (used if no custom waiting room is specified)
    location:
      world: "world"
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0

  # List of materials considered unsafe (will avoid spawning on these)
  unsafe-materials:
    - "LAVA"
    - "FIRE"
    - "CACTUS"
    - "WATER"
    - "AIR"
    - "MAGMA_BLOCK"
    - "CAMPFIRE"
    - "SOUL_CAMPFIRE"
    - "WITHER_ROSE"
    - "SWEET_BERRY_BUSH"