name: SmartSpawnPoint
version: '${version}'
main: uz.alex2276564.smartspawnpoint.SmartSpawnPoint
api-version: '1.16'
authors: [alex2276564]
softdepend: [WorldGuard, PlaceholderAPI]
commands:
  smartspawnpoint:
    description: Reload the SmartSpawnPoint configuration
    usage: /<command> reload
    permission: smartspawnpoint.reload
website: https://github.com/alex2276564/SmartSpawnPoint